## Andhra

Basic descriptive statistics about the data. And sanity checks.

```{r load_data}
andhra <- readr::read_csv("andhra.csv")
```

Number of rows:

```{r nrows}
nrow(andhra)
```

Unique Values in Sex:

```{r unique_vals_in_sex}
# Unique values in sex
table(andhra$sex)
```

Summary of Age:

```{r age}
# Age
summary(andhra$age)
```

No. of characters in ID:
```{r length_of_id}
# Length of ID
table(nchar(andhra$id))
```

Number of characters in pin code:

```{r nchar_pincode}
table(nchar(andhra$pin_code))
```

```{r total_electors}
# Net electors
sum(with(andhra, rowSums(cbind(net_electors_male, net_electors_female), na.rm = T) == net_electors_total), na.rm = T)
nrow(andhra)
```

No. of characters in elector name and checks around that:
```{r checks_elector_name_size}
## Checks that succeeded
table(nchar(andhra$elector_name))
andhra[which(nchar(andhra$elector_name) < 4), "filename"]
```

Basic admin. units:
```{r police_station_mandal_district_main_town}
table(andhra$police_station)
table(andhra$mandal)
table(andhra$district)
table(andhra$main_town)
```
