## Arunachal Pradesh

Basic descriptive statistics about the data. And sanity checks.

```{r load_data}
arunachal <- readr::read_csv("arunachal.csv")
```

Number of rows:

```{r nrows}
nrow(arunachal)
```

Unique Values in Sex:

```{r unique_vals_in_sex}
# Unique values in sex
table(arunachal$sex)
```

Summary of Age:

```{r age}
# Age
summary(arunachal$age)
```

No. of characters in ID:
```{r length_of_id}
# Length of ID
table(nchar(arunachal$id))
```

Number of characters in pin code:

```{r nchar_pincode}
table(nchar(arunachal$pin_code))
```

```{r total_electors}
# Net electors
sum(with(arunachal, rowSums(cbind(net_electors_male, net_electors_female), na.rm = T) == net_electors_total), na.rm = T)
nrow(arunachal)
```

No. of characters in elector name and checks around that:
```{r checks_elector_name_size}
## Checks that succeeded
table(nchar(arunachal$elector_name))
arunachal[which(nchar(arunachal$elector_name) < 4), "filename"]
```

Basic admin. units:
```{r police_station_mandal_district_main_town}
table(arunachal$police_station)
table(arunachal$mandal)
table(arunachal$district)
table(arunachal$main_town)
```
